version: '3'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    env_file: 
      - ./database/.env
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    hostname: database

  redis:
    image: redis:alpine
    hostname: redis

volumes:
    database-data: